import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Footer } from "@/components/layout/Footer";
import { Navbar } from "@/components/layout/Navbar";
import { getArticleBySlug } from "@/lib/articles";
import { getEmbedUrl } from "@/lib/video";

type SlugProps = { params: Promise<{ slug: string }> };
export async function generateMetadata({ params }: SlugProps): Promise<Metadata> { const { slug } = await params; const article = await getArticleBySlug(slug); return article ? { title: `${article.title} | BeritaFomo`, description: article.description } : { title: "Artikel tidak ditemukan" }; }
export default async function ArticlePage({ params }: SlugProps) { const { slug } = await params; const article = await getArticleBySlug(slug); if (!article) notFound(); const embedUrl = getEmbedUrl(article.videoUrl); return <><Navbar /><article className="mx-auto max-w-3xl px-4 py-10"><p className="text-sm font-bold uppercase tracking-wider text-orange-600">{article.category}</p><h1 className="mt-3 text-4xl font-black leading-tight text-slate-950 sm:text-5xl">{article.title}</h1><p className="mt-5 text-lg leading-8 text-slate-600">{article.description}</p><div className="mt-6 flex flex-wrap gap-3 text-sm text-slate-500"><span>Oleh <b className="text-slate-700">{article.author}</b></span><span>•</span><time dateTime={article.publishedAt}>{new Intl.DateTimeFormat("id-ID", { dateStyle: "long" }).format(new Date(article.publishedAt))}</time></div>{article.thumbnailUrl && <figure className="mt-8"><img src={article.thumbnailUrl} alt={article.thumbnailAlt} className="aspect-video w-full rounded-2xl object-cover" /><figcaption className="mt-2 text-xs text-slate-500">{article.thumbnailAlt}</figcaption></figure>}<div className="mt-8 whitespace-pre-wrap text-[1.05rem] leading-8 text-slate-800">{article.content}</div>{embedUrl && <section className="mt-10"><h2 className="mb-3 text-2xl font-black text-slate-950">Video terkait</h2><div className="aspect-video overflow-hidden rounded-2xl bg-slate-950"><iframe className="h-full w-full" src={embedUrl} title={`Video terkait: ${article.title}`} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen /></div></section>}{article.sourceUrl && <aside className="mt-10 rounded-xl border border-blue-100 bg-blue-50 p-5"><p className="font-bold text-slate-900">Sumber berita</p><a className="mt-1 inline-block text-blue-700 underline hover:text-blue-900" href={article.sourceUrl} target="_blank" rel="noreferrer">{article.sourceName || article.sourceUrl} ↗</a></aside>}</article><Footer /></>; }
